" VimVader syntax file

" #############################################################################
" #############################################################################
" Note: Be careful when merging the upstream version of this file.
"       Much of this is generated by scripts/genvimvim.lua
"       (installs to $VIMRUNTIME/syntax/vim/generated.vim)
" #############################################################################
" #############################################################################

" VimVaderTodo: contains common special-notices for comments {{{2
" Use the VimVaderCommentGroup cluster to add your own.
syn keyword VimVaderTodo contained	COMBAK	FIXME	TODO	XXX
syn cluster VimVaderCommentGroup	contains=VimVaderTodo,@Spell

" Special and plugin VimVader commands {{{2
syn match   VimVaderCommand contained	"\<z[-+^.=]\=\>"
syn keyword VimVaderOnlyCommand contained	fix[del] op[en] sh[ell] P[rint]
syn keyword VimVaderStdPlugin contained	DiffOrig Man N[ext] S TOhtml XMLent XMLns

" VimVader-specific options {{{2
syn keyword VimVaderOnlyOption contained	biosk bioskey cp compatible consk conskey cm cryptmethod edcompatible guipty key macatsui mzq mzquantum osfiletype oft renderoptions rop st shelltype sn shortname tenc termencoding ta textauto tx textmode tf ttyfast ttym ttymouse tbi ttybuiltin wiv weirdinvert

" Turn-off setting variants
syn keyword VimVaderOnlyOption contained	nobiosk nobioskey noconsk noconskey nocp nocompatible noguipty nomacatsui nosn noshortname nota notextauto notx notextmode notf nottyfast notbi nottybuiltin nowiv noweirdinvert

" Invertible setting variants
syn keyword VimVaderOnlyOption contained	invbiosk invbioskey invconsk invconskey invcp invcompatible invguipty invmacatsui invsn invshortname invta invtextauto invtx invtextmode invtf invttyfast invtbi invttybuiltin invwiv invweirdinvert
" termcap codes (which can also be set) {{{2
syn keyword VimVaderTermOption contained	t_8b t_AB t_al t_bc t_ce t_cl t_Co t_Cs t_CV t_db t_DL t_F1 t_F2 t_F3 t_F4 t_F5 t_F6 t_F7 t_F8 t_F9 t_fs t_IE t_IS t_k1 t_K1 t_k2 t_k3 t_K3 t_k4 t_K4 t_k5 t_K5 t_k6 t_K6 t_k7 t_K7 t_k8 t_K8 t_k9 t_K9 t_KA t_kb t_kB t_KB t_KC t_kd t_kD t_KD t_ke t_KE t_KF t_KG t_kh t_KH t_kI t_KI t_KJ t_KK t_kl t_KL t_kN t_kP t_kr t_ks t_ku t_le t_mb t_md t_me t_mr t_ms t_nd t_op t_RB t_RI t_RV t_Sb t_se t_Sf t_SI t_so t_sr t_SR t_te t_ti t_ts t_u7 t_ue t_us t_ut t_vb t_ve t_vi t_vs t_WP t_WS t_xn t_xs t_ZH t_ZR
syn keyword VimVaderTermOption contained	t_8f t_AF t_AL t_cd t_Ce t_cm t_cs t_CS t_da t_dl t_EI
syn match   VimVaderTermOption contained	"t_%1"
syn match   VimVaderTermOption contained	"t_#2"
syn match   VimVaderTermOption contained	"t_#4"
syn match   VimVaderTermOption contained	"t_@7"
syn match   VimVaderTermOption contained	"t_*7"
syn match   VimVaderTermOption contained	"t_&8"
syn match   VimVaderTermOption contained	"t_%i"
syn match   VimVaderTermOption contained	"t_k;"

" unsupported settings: these are supported by vi but don't do anything in VimVader {{{2
syn keyword VimVaderErrSetting contained	hardtabs ht w1200 w300 w9600
"}}}2
syn case ignore
" Highlight commonly used Groupnames {{{2
syn keyword VimVaderGroup contained	Comment Constant String Character Number Boolean Float Identifier Function Statement Conditional Repeat Label Operator Keyword Exception PreProc Include Define Macro PreCondit Type StorageClass Structure Typedef Special SpecialChar Tag Delimiter SpecialComment Debug Underlined Ignore Error Todo

" Default highlighting groups {{{2
syn keyword VimVaderHLGroup contained	ColorColumn Cursor CursorColumn CursorIM CursorLine CursorLineNr DiffAdd DiffChange DiffDelete DiffText Directory EndOfBuffer ErrorMsg FoldColumn Folded IncSearch LineNr MatchParen Menu ModeMsg MoreMsg NonText Normal Pmenu PmenuSbar PmenuSel PmenuThumb Question Scrollbar Search SignColumn SpecialKey SpellBad SpellCap SpellLocal SpellRare StatusLine StatusLineNC TabLine TabLineFill TabLineSel Title Tooltip VertSplit Visual WarningMsg WildMenu
syn match VimVaderHLGroup contained	"Conceal"
syn keyword VimVaderOnlyHLGroup contained	VisualNOS
syn keyword nvimHLGroup contained	Substitute TermCursor TermCursorNC QuickFixLine
"}}}2
syn case match
" Special VimVader Highlighting (not automatic) {{{1

" commands not picked up by the generator (due to non-standard format)
syn keyword VimVaderCommand contained	py3

" Numbers {{{2
" =======
syn match VimVaderNumber	"\<\d\+\%(\.\d\+\%([eE][+-]\=\d\+\)\=\)\=" skipwhite nextgroup=VimVaderGlobal,vimSubst,vimCommand,vimComment
syn match VimVaderNumber	"-\d\+\%(\.\d\+\%([eE][+-]\=\d\+\)\=\)\="  skipwhite nextgroup=VimVaderGlobal,vimSubst,vimCommand,vimComment
syn match VimVaderNumber	"\<0[xX]\x\+"		       skipwhite nextgroup=VimVaderGlobal,vimSubst,vimCommand,vimComment
syn match VimVaderNumber	"\%(^\|\A\)\zs#\x\{6}"             	       skipwhite nextgroup=VimVaderGlobal,vimSubst,vimCommand,vimComment

" All VimVaderCommands are contained by VimVaderIsCommand. {{{2
syn match VimVaderCmdSep	"[:|]\+"	skipwhite nextgroup=VimVaderAddress,vimAutoCmd,vimEcho,vimIsCommand,vimExtCmd,vimFilter,vimLet,vimMap,vimMark,vimSet,vimSyntax,vimUserCmd
syn match VimVaderIsCommand	"\<\h\w*\>"	contains=VimVaderCommand
syn match VimVaderVar	      contained	"\<\h[a-zA-Z0-9#_]*\>"
syn match VimVaderVar		"\<[bwglstav]:\h[a-zA-Z0-9#_]*\>"
syn match VimVaderVar	      	"\s\zs&\a\+\>"
syn match VimVaderFBVar      contained   "\<[bwglstav]:\h[a-zA-Z0-9#_]*\>"
syn keyword VimVaderCommand  contained	in

" Insertions And Appends: insert append {{{2
" =======================
syn region VimVaderInsert	matchgroup=VimVaderCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=a\%[ppend]$"		matchgroup=VimVaderCommand end="^\.$""
syn region VimVaderInsert	matchgroup=VimVaderCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=c\%[hange]$"		matchgroup=VimVaderCommand end="^\.$""
syn region VimVaderInsert	matchgroup=VimVaderCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=i\%[nsert]$"		matchgroup=VimVaderCommand end="^\.$""
syn region VimVaderInsert	matchgroup=VimVaderCommand start="^[: \t]*\(\d\+\(,\d\+\)\=\)\=starti\%[nsert]$"	matchgroup=VimVaderCommand end="^\.$""

" Behave! {{{2
" =======
syn match   VimVaderBehave	"\<be\%[have]\>" skipwhite nextgroup=VimVaderBehaveModel,vimBehaveError
syn keyword VimVaderBehaveModel contained	mswin	xterm

" Filetypes {{{2
" =========
syn match   VimVaderFiletype	"\<filet\%[ype]\(\s\+\I\i*\)*"	skipwhite contains=VimVaderFTCmd,vimFTOption,vimFTError
syn keyword VimVaderFTCmd    contained	filet[ype]
syn keyword VimVaderFTOption contained	detect indent off on plugin

" Augroup : VimVaderAugroupError removed because long augroups caused sync'ing problems. {{{2
" ======= : Trade-off: Increasing synclines with slower editing vs augroup END error checking.
syn cluster VimVaderAugroupList	contains=VimVaderAugroup,vimIsCommand,vimUserCmd,vimExecute,vimNotFunc,vimFuncName,vimFunction,vimFunctionError,vimLineComment,vimNotFunc,vimMap,vimSpecFile,vimOper,vimNumber,vimOperParen,vimComment,vimString,vimSubst,vimMark,vimRegister,vimAddress,vimFilter,vimCmplxRepeat,vimComment,vimLet,vimSet,vimAutoCmd,vimRegion,vimSynLine,vimNotation,vimCtrlChar,vimFuncVar,vimContinue,vimSetEqual,vimOption
syn match   VimVaderAugroup	"aug\%[roup]!"	contains=VimVaderAugroupKey
syn keyword VimVaderAugroupKey contained	aug[roup]

" Operators: {{{2
" =========
syn cluster	VimVaderOperGroup	contains=VimVaderEnvvar,vimFunc,vimFuncVar,vimOper,vimOperParen,vimNumber,vimString,vimRegister,vimContinue
syn match	VimVaderOper	"\%#=1\(==\|!=\|>=\|<=\|=\~\|!\~\|>\|<\|=\)[?#]\{0,2}"	skipwhite nextgroup=VimVaderString,vimSpecFile
syn match	VimVaderOper	"\(\<is\|\<isnot\)[?#]\{0,2}\>"			skipwhite nextgroup=VimVaderString,vimSpecFile
syn match	VimVaderOper	"||\|&&\|[-+.!]"				skipwhite nextgroup=VimVaderString,vimSpecFile
syn region	VimVaderOperParen 	matchgroup=VimVaderParenSep	start="(" end=")" contains=@vimOperGroup
syn region	VimVaderOperParen	matchgroup=VimVaderSep		start="{" end="}" contains=@vimOperGroup nextgroup=VimVaderVar,vimFuncVar

" Functions : Tag is provided for those who wish to highlight tagged functions {{{2
" =========
syn cluster	VimVaderFuncList	contains=VimVaderCommand,vimFunctionError,vimFuncKey,Tag,vimFuncSID
syn cluster	VimVaderFuncBodyList	contains=VimVaderAbb,vimAddress,vimAugroupKey,vimAutoCmd,vimCmplxRepeat,vimComment,vimContinue,vimCtrlChar,vimEcho,vimEchoHL,vimExecute,vimIsCommand,vimFBVar,vimFunc,vimFunction,vimFuncVar,vimGlobal,vimHighlight,vimIsCommand,vimLet,vimLineComment,vimMap,vimMark,vimNorm,vimNotation,vimNotFunc,vimNumber,vimOper,vimOperParen,vimRegion,vimRegister,vimSearch,vimSet,vimSpecFile,vimString,vimSubst,vimSynLine,vimUnmap,vimUserCommand
syn match	VimVaderFunction	"\<fu\%[nction]!\=\s\+\%(<[sS][iI][dD]>\|[sSgGbBwWtTlL]:\)\=\%(\i\|[#.]\|{.\{-1,}}\)*\ze\s*("	contains=@vimFuncList nextgroup=VimVaderFuncBody

syn region	VimVaderFuncBody  contained	start="\ze\s*("	matchgroup=VimVaderCommand end="\<\(endf\>\|endfu\%[nction]\>\)"		contains=@vimFuncBodyList
syn match	VimVaderFuncVar   contained	"a:\(\K\k*\|\d\+\)"
syn match	VimVaderFuncSID   contained	"\c<sid>\|\<s:"
syn keyword	VimVaderFuncKey   contained	fu[nction]
syn match	VimVaderFuncBlank contained	"\s\+"

syn keyword	VimVaderPattern   contained	start	skip	end

" Special Filenames, Modifiers, Extension Removal: {{{2
" ===============================================
syn match	VimVaderSpecFile	"<c\(word\|WORD\)>"	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFile	"<\([acs]file\|amatch\|abuf\)>"	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFile	"\s%[ \t:]"ms=s+1,me=e-1	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFile	"\s%$"ms=s+1	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFile	"\s%<"ms=s+1,me=e-1	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFile	"#\d\+\|[#%]<\>"	nextgroup=VimVaderSpecFileMod,vimSubst
syn match	VimVaderSpecFileMod	"\(:[phtre]\)\+"	contained

" User-Specified Commands: {{{2
" =======================
syn cluster	VimVaderUserCmdList	contains=VimVaderAddress,vimSyntax,vimHighlight,vimAutoCmd,vimCmplxRepeat,vimComment,vimCtrlChar,vimEscapeBrace,vimFunc,vimFuncName,vimFunction,vimFunctionError,vimIsCommand,vimMark,vimNotation,vimNumber,vimOper,vimRegion,vimRegister,vimLet,vimSet,vimSetEqual,vimSetString,vimSpecFile,vimString,vimSubst,vimSubstRep,vimSubstRange,vimSynLine
syn keyword	VimVaderUserCommand	contained	com[mand]
syn match	VimVaderUserCmd	"\<com\%[mand]!\=\>.*$"	contains=VimVaderUserAttrb,vimUserAttrbError,vimUserCommand,@vimUserCmdList
syn match	VimVaderUserAttrbError	contained	"-\a\+\ze\s"
syn match	VimVaderUserAttrb	contained	"-nargs=[01*?+]"	contains=VimVaderUserAttrbKey,vimOper
syn match	VimVaderUserAttrb	contained	"-complete="		contains=VimVaderUserAttrbKey,vimOper nextgroup=VimVaderUserAttrbCmplt,vimUserCmdError
syn match	VimVaderUserAttrb	contained	"-range\(=%\|=\d\+\)\="	contains=VimVaderNumber,vimOper,vimUserAttrbKey
syn match	VimVaderUserAttrb	contained	"-count\(=\d\+\)\="	contains=VimVaderNumber,vimOper,vimUserAttrbKey
syn match	VimVaderUserAttrb	contained	"-bang\>"		contains=VimVaderOper,vimUserAttrbKey
syn match	VimVaderUserAttrb	contained	"-bar\>"		contains=VimVaderOper,vimUserAttrbKey
syn match	VimVaderUserAttrb	contained	"-buffer\>"		contains=VimVaderOper,vimUserAttrbKey
syn match	VimVaderUserAttrb	contained	"-register\>"		contains=VimVaderOper,vimUserAttrbKey
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_nousercmderror")
 syn match	VimVaderUserCmdError	contained	"\S\+\>"
endif
syn case ignore
syn keyword	VimVaderUserAttrbKey   contained	bar	ban[g]	cou[nt]	ra[nge] com[plete]	n[args]	re[gister]
syn keyword	VimVaderUserAttrbCmplt contained	augroup buffer behave color command compiler cscope dir environment event expression file file_in_path filetype function help highlight history locale mapping menu option packadd shellcmd sign syntax syntime tag tag_listfiles user var
syn keyword	VimVaderUserAttrbCmplt contained	custom customlist nextgroup=VimVaderUserAttrbCmpltFunc,vimUserCmdError
syn match	VimVaderUserAttrbCmpltFunc contained	",\%([sS]:\|<[sS][iI][dD]>\)\=\%(\h\w*\%(#\h\w*\)\+\|\h\w*\)"hs=s+1 nextgroup=VimVaderUserCmdError

syn case match
syn match	VimVaderUserAttrbCmplt contained	"custom,\u\w*"

" Lower Priority Comments: after some VimVader commands... {{{2
" =======================
syn match	VimVaderComment	excludenl +\s"[^\-:.%#=*].*$+lc=1	contains=@vimCommentGroup,vimCommentString
syn match	VimVaderComment	+\<endif\s\+".*$+lc=5	contains=@vimCommentGroup,vimCommentString
syn match	VimVaderComment	+\<else\s\+".*$+lc=4	contains=@vimCommentGroup,vimCommentString
syn region	VimVaderCommentString	contained oneline start='\S\s\+"'ms=e	end='"'

" Environment Variables: {{{2
" =====================
syn match	VimVaderEnvvar	"\$\I\i*"
syn match	VimVaderEnvvar	"\${\I\i*}"

" In-String Specials: {{{2
" Try to catch strings, if nothing else matches (therefore it must precede the others!)
"  VimVaderEscapeBrace handles ["]  []"] (ie. "s don't terminate string inside [])
syn region	VimVaderEscapeBrace	oneline   contained transparent start="[^\\]\(\\\\\)*\[\zs\^\=\]\=" skip="\\\\\|\\\]" end="]"me=e-1
syn match	VimVaderPatSepErr	contained	"\\)"
syn match	VimVaderPatSep	contained	"\\|"
syn region	VimVaderPatSepZone	oneline   contained   matchgroup=VimVaderPatSepZ start="\\%\=\ze(" skip="\\\\" end="\\)\|[^\\]['"]"	contains=@vimStringGroup
syn region	VimVaderPatRegion	contained transparent matchgroup=VimVaderPatSepR start="\\[z%]\=(" end="\\)"	contains=@vimSubstList oneline
syn match	VimVaderNotPatSep	contained	"\\\\"
syn cluster	VimVaderStringGroup	contains=VimVaderEscapeBrace,vimPatSep,vimNotPatSep,vimPatSepErr,vimPatSepZone,@Spell
syn region	VimVaderString	oneline keepend	start=+[^a-zA-Z>!\\@]"+lc=1 skip=+\\\\\|\\"+ matchgroup=VimVaderStringEnd end=+"+	contains=@vimStringGroup
syn region	VimVaderString	oneline keepend	start=+[^a-zA-Z>!\\@]'+lc=1 end=+'+
syn region	VimVaderString	oneline	start=+=!+lc=1	skip=+\\\\\|\\!+ end=+!+	contains=@vimStringGroup
syn region	VimVaderString	oneline	start="=+"lc=1	skip="\\\\\|\\+" end="+"	contains=@vimStringGroup
syn region	VimVaderString	oneline	start="\s/\s*\A"lc=1 skip="\\\\\|\\+" end="/"	contains=@vimStringGroup
syn match	VimVaderString	contained	+"[^"]*\\$+	skipnl nextgroup=VimVaderStringCont
syn match	VimVaderStringCont	contained	+\(\\\\\|.\)\{-}[^\\]"+

" Substitutions: {{{2
" =============
syn cluster	VimVaderSubstList	contains=VimVaderPatSep,vimPatRegion,vimPatSepErr,vimSubstTwoBS,vimSubstRange,vimNotation
syn cluster	VimVaderSubstRepList	contains=VimVaderSubstSubstr,vimSubstTwoBS,vimNotation
syn cluster	VimVaderSubstList	add=VimVaderCollection
syn match	VimVaderSubst	"\(:\+\s*\|^\s*\||\s*\)\<\%(\<s\%[ubstitute]\>\|\<sm\%[agic]\>\|\<sno\%[magic]\>\)[:#[:alpha:]]\@!" nextgroup=VimVaderSubstPat
syn match	VimVaderSubst	"\%(^\|[^\\]\)\<s\%[ubstitute]\>[:#[:alpha:]]\@!"	nextgroup=VimVaderSubstPat contained
syn match	VimVaderSubst	"/\zs\<s\%[ubstitute]\>\ze/"		nextgroup=VimVaderSubstPat
syn match	VimVaderSubst	"\(:\+\s*\|^\s*\)s\ze#.\{-}#.\{-}#"		nextgroup=VimVaderSubstPat
syn match	VimVaderSubst1       contained	"\<s\%[ubstitute]\>"	nextgroup=VimVaderSubstPat
syn match	VimVaderSubst2       contained	"s\%[ubstitute]\>"	nextgroup=VimVaderSubstPat
syn region	VimVaderSubstPat     contained	matchgroup=VimVaderSubstDelim start="\z([^a-zA-Z( \t[\]&]\)"rs=s+1 skip="\\\\\|\\\z1" end="\z1"re=e-1,me=e-1	 contains=@vimSubstList	nextgroup=VimVaderSubstRep4	oneline
syn region	VimVaderSubstRep4    contained	matchgroup=VimVaderSubstDelim start="\z(.\)" skip="\\\\\|\\\z1" end="\z1" matchgroup=VimVaderNotation end="<[cC][rR]>" contains=@vimSubstRepList	nextgroup=VimVaderSubstFlagErr	oneline
syn region	VimVaderCollection   contained transparent	start="\\\@<!\[" skip="\\\[" end="\]"	contains=VimVaderCollClass
syn match	VimVaderCollClassErr contained	"\[:.\{-\}:\]"
syn match	VimVaderCollClass    contained transparent	"\%#=1\[:\(alnum\|alpha\|blank\|cntrl\|digit\|graph\|lower\|print\|punct\|space\|upper\|xdigit\|return\|tab\|escape\|backspace\):\]"
syn match	VimVaderSubstSubstr  contained	"\\z\=\d"
syn match	VimVaderSubstTwoBS   contained	"\\\\"
syn match	VimVaderSubstFlagErr contained	"[^< \t\r|]\+" contains=VimVaderSubstFlags
syn match	VimVaderSubstFlags   contained	"[&cegiIpr]\+"

" 'String': {{{2
syn match	VimVaderString	"[^(,]'[^']\{-}\zs'"

" Marks, Registers, Addresses, Filters: {{{2
syn match	VimVaderMark	"'[a-zA-Z0-9]\ze[-+,!]"	nextgroup=VimVaderFilter,vimMarkNumber,vimSubst
syn match	VimVaderMark	"'[<>]\ze[-+,!]"		nextgroup=VimVaderFilter,vimMarkNumber,vimSubst
syn match	VimVaderMark	",\zs'[<>]\ze"		nextgroup=VimVaderFilter,vimMarkNumber,vimSubst
syn match	VimVaderMark	"[!,:]\zs'[a-zA-Z0-9]"	nextgroup=VimVaderFilter,vimMarkNumber,vimSubst
syn match	VimVaderMark	"\<norm\%[al]\s\zs'[a-zA-Z0-9]"	nextgroup=VimVaderFilter,vimMarkNumber,vimSubst
syn match	VimVaderMarkNumber	"[-+]\d\+"		contained contains=VimVaderOper nextgroup=VimVaderSubst2
syn match	VimVaderPlainMark contained	"'[a-zA-Z0-9]"
syn match	VimVaderRange	"[`'][a-zA-Z0-9],[`'][a-zA-Z0-9]"	contains=VimVaderMark	skipwhite nextgroup=VimVaderFilter

syn match	VimVaderRegister	'[^,;[{: \t]\zs"[a-zA-Z0-9.%#:_\-/]\ze[^a-zA-Z_":0-9]'
syn match	VimVaderRegister	'\<norm\s\+\zs"[a-zA-Z0-9]'
syn match	VimVaderRegister	'\<normal\s\+\zs"[a-zA-Z0-9]'
syn match	VimVaderRegister	'@"'
syn match	VimVaderPlainRegister contained	'"[a-zA-Z0-9\-:.%#*+=]'

syn match	VimVaderAddress	",\zs[.$]"	skipwhite nextgroup=VimVaderSubst1
syn match	VimVaderAddress	"%\ze\a"	skipwhite nextgroup=VimVaderString,vimSubst1

syn match	VimVaderFilter 		"^!!\=[^"]\{-}\(|\|\ze\"\|$\)"	contains=VimVaderOper,vimSpecFile
syn match	VimVaderFilter contained	"!!\=[^"]\{-}\(|\|\ze\"\|$\)"	contains=VimVaderOper,vimSpecFile

" Complex repeats (:h complex-repeat) {{{2
syn match	VimVaderCmplxRepeat	'[^a-zA-Z_/\\()]q[0-9a-zA-Z"]\>'lc=1
syn match	VimVaderCmplxRepeat	'@[0-9a-z".=@:]\ze\($\|[^a-zA-Z]\>\)'

" Set command and associated set-options (vimOptions) with comment {{{2
syn region	VimVaderSet		matchgroup=VimVaderCommand start="\<\%(setl\%[ocal]\|setg\%[lobal]\|se\%[t]\)\>" skip="\%(\\\\\)*\\." end="$" end="|" matchgroup=VimVaderNotation end="<[cC][rR]>" keepend oneline contains=VimVaderSetEqual,vimOption,vimErrSetting,vimComment,vimSetString,vimSetMod
syn region	VimVaderSetEqual	contained	start="[=:]\|[-+^]=" skip="\\\\\|\\\s" end="[| \t]\|$"me=e-1	contains=VimVaderCtrlChar,vimSetSep,vimNotation,vimEnvvar oneline
syn region	VimVaderSetString	contained	start=+="+hs=s+1	skip=+\\\\\|\\"+  end=+"+		contains=VimVaderCtrlChar
syn match	VimVaderSetSep	contained	"[,:]" skipwhite nextgroup=VimVaderCommand
syn match	VimVaderSetMod	contained	"&vim\=\|[!&?<]\|all&"

" Let {{{2
" ===
syn keyword	VimVaderLet	let	unl[et]	skipwhite nextgroup=VimVaderVar,vimFuncVar

" Abbreviations {{{2
" =============
syn keyword VimVaderAbb	ab[breviate] ca[bbrev] inorea[bbrev] cnorea[bbrev] norea[bbrev] ia[bbrev] skipwhite nextgroup=VimVaderMapMod,vimMapLhs

" Autocmd {{{2
" =======
syn match	VimVaderAutoEventList	contained	"\(!\s\+\)\=\(\a\+,\)*\a\+"	contains=VimVaderAutoEvent,nvimAutoEvent nextgroup=VimVaderAutoCmdSpace
syn match	VimVaderAutoCmdSpace	contained	"\s\+"	nextgroup=VimVaderAutoCmdSfxList
syn match	VimVaderAutoCmdSfxList	contained	"\S*"
syn keyword	VimVaderAutoCmd	au[tocmd] do[autocmd] doautoa[ll]	skipwhite nextgroup=VimVaderAutoEventList

" Echo and Execute -- prefer strings! {{{2
" ================
syn region	VimVaderEcho	oneline excludenl matchgroup=VimVaderCommand start="\<ec\%[ho]\>" skip="\(\\\\\)*\\|" end="$\||" contains=VimVaderFunc,vimFuncVar,vimString,vimVar
syn region	VimVaderExecute	oneline excludenl matchgroup=VimVaderCommand start="\<exe\%[cute]\>" skip="\(\\\\\)*\\|" end="$\||\|<[cC][rR]>" contains=VimVaderFuncVar,vimIsCommand,vimOper,vimNotation,vimOperParen,vimString,vimVar
syn match	VimVaderEchoHL	"echohl\="	skipwhite nextgroup=VimVaderGroup,vimHLGroup,vimEchoHLNone,vimOnlyHLGroup,nvimHLGroup
syn case ignore
syn keyword	VimVaderEchoHLNone	none
syn case match

" Maps {{{2
" ====
syn match	VimVaderMap		"\<map\>!\=\ze\s*[^(]" skipwhite nextgroup=VimVaderMapMod,vimMapLhs
syn keyword	VimVaderMap		cm[ap] cno[remap] im[ap] ino[remap] lm[ap] ln[oremap] nm[ap] nn[oremap] no[remap] om[ap] ono[remap] smap snor[emap] vm[ap] vn[oremap] xm[ap] xn[oremap] skipwhite nextgroup=VimVaderMapBang,vimMapMod,vimMapLhs
syn keyword	nvimMap		tn[oremap] tm[ap] skipwhite nextgroup=VimVaderMapBang,vimMapMod,vimMapLhs
syn keyword	VimVaderMap		mapc[lear] smapc[lear]
syn keyword	VimVaderUnmap		cu[nmap] iu[nmap] lu[nmap] nun[map] ou[nmap] sunm[ap] unm[ap] unm[ap] vu[nmap] xu[nmap] skipwhite nextgroup=VimVaderMapBang,vimMapMod,vimMapLhs
syn keyword	nvimUnmap 		tunm[ap] skipwhite nextgroup=VimVaderMapBang,vimMapMod,vimMapLhs
syn match	VimVaderMapLhs	contained	"\S\+"			contains=VimVaderNotation,vimCtrlChar skipwhite nextgroup=VimVaderMapRhs
syn match	VimVaderMapBang	contained	"!"			skipwhite nextgroup=VimVaderMapMod,vimMapLhs
syn match	VimVaderMapMod	contained	"\%#=1\c<\(buffer\|expr\|\(local\)\=leader\|nowait\|plug\|script\|sid\|unique\|silent\)\+>" contains=VimVaderMapModKey,vimMapModErr skipwhite nextgroup=VimVaderMapMod,vimMapLhs
syn match	VimVaderMapRhs	contained	".*" contains=VimVaderNotation,vimCtrlChar	skipnl nextgroup=VimVaderMapRhsExtend
syn match	VimVaderMapRhsExtend	contained	"^\s*\\.*$"			contains=VimVaderContinue
syn case ignore
syn keyword	VimVaderMapModKey	contained	buffer	expr	leader	localleader	nowait	plug	script	sid	silent	unique
syn case match

" Menus {{{2
" =====
syn cluster	VimVaderMenuList contains=VimVaderMenuBang,vimMenuPriority,vimMenuName,vimMenuMod
syn keyword	VimVaderCommand	am[enu] an[oremenu] aun[menu] cme[nu] cnoreme[nu] cunme[nu] ime[nu] inoreme[nu] iunme[nu] me[nu] nme[nu] nnoreme[nu] noreme[nu] nunme[nu] ome[nu] onoreme[nu] ounme[nu] unme[nu] vme[nu] vnoreme[nu] vunme[nu] skipwhite nextgroup=@vimMenuList
syn match	VimVaderMenuName	"[^ \t\\<]\+"	contained nextgroup=VimVaderMenuNameMore,vimMenuMap
syn match	VimVaderMenuPriority	"\d\+\(\.\d\+\)*"	contained skipwhite nextgroup=VimVaderMenuName
syn match	VimVaderMenuNameMore	"\c\\\s\|<tab>\|\\\."	contained nextgroup=VimVaderMenuName,vimMenuNameMore contains=VimVaderNotation
syn match	VimVaderMenuMod    contained	"\c<\(script\|silent\)\+>"  skipwhite contains=VimVaderMapModKey,vimMapModErr nextgroup=@vimMenuList
syn match	VimVaderMenuMap	"\s"	contained skipwhite nextgroup=VimVaderMenuRhs
syn match	VimVaderMenuRhs	".*$"	contained contains=VimVaderString,vimComment,vimIsCommand
syn match	VimVaderMenuBang	"!"	contained skipwhite nextgroup=@vimMenuList

" Angle-Bracket Notation (tnx to Michael Geddes) {{{2
" ======================
syn case ignore
syn match	VimVaderNotation	"\%#=1\(\\\|<lt>\)\=<\([scamd]-\)\{0,4}x\=\(f\d\{1,2}\|[^ \t:]\|cmd\|cr\|lf\|linefeed\|return\|k\=del\%[ete]\|bs\|backspace\|tab\|esc\|right\|left\|help\|undo\|insert\|ins\|mouse\|k\=home\|k\=end\|kplus\|kminus\|kdivide\|kmultiply\|kenter\|kpoint\|space\|k\=\(page\)\=\(\|down\|up\|k\d\>\)\)>" contains=VimVaderBracket
syn match	VimVaderNotation	"\%#=1\(\\\|<lt>\)\=<\([scam2-4]-\)\{0,4}\(right\|left\|middle\)\(mouse\)\=\(drag\|release\)\=>"	contains=VimVaderBracket
syn match	VimVaderNotation	"\%#=1\(\\\|<lt>\)\=<\(bslash\|plug\|sid\|space\|bar\|nop\|nul\|lt\)>"			contains=VimVaderBracket
syn match	VimVaderNotation	'\(\\\|<lt>\)\=<C-R>[0-9a-z"%#:.\-=]'he=e-1				contains=VimVaderBracket
syn match	VimVaderNotation	'\%#=1\(\\\|<lt>\)\=<\%(q-\)\=\(line[12]\|count\|bang\|reg\|args\|mods\|f-args\|f-mods\|lt\)>'	contains=VimVaderBracket
syn match	VimVaderNotation	"\%#=1\(\\\|<lt>\)\=<\([cas]file\|abuf\|amatch\|cword\|cWORD\|client\)>"		contains=VimVaderBracket
syn match	VimVaderBracket contained	"[\\<>]"
syn case match

" User Function Highlighting {{{2
" (following Gautam Iyer's suggestion)
" ==========================
syn match VimVaderFunc		"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\ze\s*("		contains=VimVaderFuncName,vimUserFunc,vimExecute
syn match VimVaderUserFunc contained	"\%(\%([sSgGbBwWtTlL]:\|<[sS][iI][dD]>\)\=\%(\w\+\.\)*\I[a-zA-Z0-9_.]*\)\|\<\u[a-zA-Z0-9.]*\>\|\<if\>"	contains=VimVaderNotation

" Errors And Warnings: {{{2
" ====================
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_novimfunctionerror")
 syn match	VimVaderFunctionError	"\s\zs[a-z0-9]\i\{-}\ze\s*("			contained contains=VimVaderFuncKey,vimFuncBlank
 syn match	VimVaderFunctionError	"\s\zs\%(<[sS][iI][dD]>\|[sSgGbBwWtTlL]:\)\d\i\{-}\ze\s*("	contained contains=VimVaderFuncKey,vimFuncBlank
 syn match	VimVaderElseIfErr	"\<else\s\+if\>"
 syn match	VimVaderBufnrWarn	/\<bufnr\s*(\s*["']\.['"]\s*)/
endif

syn match VimVaderNotFunc	"\<if\>\|\<el\%[seif]\>\|\<return\>\|\<while\>"	skipwhite nextgroup=VimVaderOper,vimOperParen,vimVar,vimFunc,vimNotation

" Norm {{{2
" ====
syn match	VimVaderNorm		"\<norm\%[al]!\=" skipwhite nextgroup=VimVaderNormCmds
syn match	VimVaderNormCmds contained	".*$"

" Syntax {{{2
"=======
syn match	VimVaderGroupList	contained	"@\=[^ \t,]*"	contains=VimVaderGroupSpecial,vimPatSep
syn match	VimVaderGroupList	contained	"@\=[^ \t,]*,"	nextgroup=VimVaderGroupList contains=VimVaderGroupSpecial,vimPatSep
syn keyword	VimVaderGroupSpecial	contained	ALL	ALLBUT	CONTAINED	TOP
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_novimsynerror")
 syn match	VimVaderSynError	contained	"\i\+"
 syn match	VimVaderSynError	contained	"\i\+="	nextgroup=VimVaderGroupList
endif
syn match	VimVaderSynContains	contained	"\<contain\(s\|edin\)="	nextgroup=VimVaderGroupList
syn match	VimVaderSynKeyContainedin	contained	"\<containedin="	nextgroup=VimVaderGroupList
syn match	VimVaderSynNextgroup	contained	"nextgroup="	nextgroup=VimVaderGroupList

syn match	VimVaderSyntax	"\<sy\%[ntax]\>"	contains=VimVaderCommand skipwhite nextgroup=VimVaderSynType,vimComment
syn match	VimVaderAuSyntax	contained	"\s+sy\%[ntax]"	contains=VimVaderCommand skipwhite nextgroup=VimVaderSynType,vimComment
syn cluster VimVaderFuncBodyList add=VimVaderSyntax

" Syntax: case {{{2
syn keyword	VimVaderSynType	contained	case	skipwhite nextgroup=VimVaderSynCase,vimSynCaseError
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_novimsyncaseerror")
 syn match	VimVaderSynCaseError	contained	"\i\+"
endif
syn keyword	VimVaderSynCase	contained	ignore	match

" Syntax: clear {{{2
syn keyword	VimVaderSynType	contained	clear	skipwhite nextgroup=VimVaderGroupList

" Syntax: cluster {{{2
syn keyword	VimVaderSynType	contained	cluster	skipwhite nextgroup=VimVaderClusterName
syn region	VimVaderClusterName	contained	matchgroup=VimVaderGroupName start="\h\w*" skip="\\\\\|\\|" matchgroup=VimVaderSep end="$\||" contains=VimVaderGroupAdd,vimGroupRem,vimSynContains,vimSynError
syn match	VimVaderGroupAdd	contained	"add="	nextgroup=VimVaderGroupList
syn match	VimVaderGroupRem	contained	"remove="	nextgroup=VimVaderGroupList
syn cluster VimVaderFuncBodyList add=VimVaderSynType,vimGroupAdd,vimGroupRem

" Syntax: iskeyword {{{2
syn keyword	VimVaderSynType	contained	iskeyword	skipwhite nextgroup=VimVaderIskList
syn match	VimVaderIskList	contained	'\S\+'	contains=VimVaderIskSep
syn match	VimVaderIskSep	contained	','

" Syntax: include {{{2
syn keyword	VimVaderSynType	contained	include	skipwhite nextgroup=VimVaderGroupList
syn cluster VimVaderFuncBodyList add=VimVaderSynType

" Syntax: keyword {{{2
syn cluster	VimVaderSynKeyGroup	contains=VimVaderSynNextgroup,vimSynKeyOpt,vimSynKeyContainedin
syn keyword	VimVaderSynType	contained	keyword	skipwhite nextgroup=VimVaderSynKeyRegion
syn region	VimVaderSynKeyRegion	contained oneline keepend	matchgroup=VimVaderGroupName start="\h\w*" skip="\\\\\|\\|" matchgroup=VimVaderSep end="|\|$" contains=@vimSynKeyGroup
syn match	VimVaderSynKeyOpt	contained	"\%#=1\<\(conceal\|contained\|transparent\|skipempty\|skipwhite\|skipnl\)\>"
syn cluster VimVaderFuncBodyList add=VimVaderSynType

" Syntax: match {{{2
syn cluster	VimVaderSynMtchGroup	contains=VimVaderMtchComment,vimSynContains,vimSynError,vimSynMtchOpt,vimSynNextgroup,vimSynRegPat,vimNotation
syn keyword	VimVaderSynType	contained	match	skipwhite nextgroup=VimVaderSynMatchRegion
syn region	VimVaderSynMatchRegion	contained keepend	matchgroup=VimVaderGroupName start="\h\w*" matchgroup=VimVaderSep end="|\|$" contains=@vimSynMtchGroup
syn match	VimVaderSynMtchOpt	contained	"\%#=1\<\(conceal\|transparent\|contained\|excludenl\|keepend\|skipempty\|skipwhite\|display\|extend\|skipnl\|fold\)\>"
if has("conceal")
 syn match	VimVaderSynMtchOpt	contained	"\<cchar="	nextgroup=VimVaderSynMtchCchar
 syn match	VimVaderSynMtchCchar	contained	"\S"
endif
syn cluster VimVaderFuncBodyList add=VimVaderSynMtchGroup

" Syntax: off and on {{{2
syn keyword	VimVaderSynType	contained	enable	list	manual	off	on	reset

" Syntax: region {{{2
syn cluster	VimVaderSynRegPatGroup	contains=VimVaderPatSep,vimNotPatSep,vimSynPatRange,vimSynNotPatRange,vimSubstSubstr,vimPatRegion,vimPatSepErr,vimNotation
syn cluster	VimVaderSynRegGroup	contains=VimVaderSynContains,vimSynNextgroup,vimSynRegOpt,vimSynReg,vimSynMtchGrp
syn keyword	VimVaderSynType	contained	region	skipwhite nextgroup=VimVaderSynRegion
syn region	VimVaderSynRegion	contained keepend	matchgroup=VimVaderGroupName start="\h\w*" skip="\\\\\|\\|" end="|\|$" contains=@vimSynRegGroup
syn match	VimVaderSynRegOpt	contained	"\%#=1\<\(conceal\(ends\)\=\|transparent\|contained\|excludenl\|skipempty\|skipwhite\|display\|keepend\|oneline\|extend\|skipnl\|fold\)\>"
syn match	VimVaderSynReg	contained	"\(start\|skip\|end\)="he=e-1	nextgroup=VimVaderSynRegPat
syn match	VimVaderSynMtchGrp	contained	"matchgroup="	nextgroup=VimVaderGroup,vimHLGroup,vimOnlyHLGroup,nvimHLGroup
syn region	VimVaderSynRegPat	contained extend	start="\z([-`~!@#$%^&*_=+;:'",./?]\)"  skip="\\\\\|\\\z1"  end="\z1"  contains=@vimSynRegPatGroup skipwhite nextgroup=VimVaderSynPatMod,vimSynReg
syn match	VimVaderSynPatMod	contained	"\%#=1\(hs\|ms\|me\|hs\|he\|rs\|re\)=[se]\([-+]\d\+\)\="
syn match	VimVaderSynPatMod	contained	"\%#=1\(hs\|ms\|me\|hs\|he\|rs\|re\)=[se]\([-+]\d\+\)\=," nextgroup=VimVaderSynPatMod
syn match	VimVaderSynPatMod	contained	"lc=\d\+"
syn match	VimVaderSynPatMod	contained	"lc=\d\+," nextgroup=VimVaderSynPatMod
syn region	VimVaderSynPatRange	contained	start="\["	skip="\\\\\|\\]"   end="]"
syn match	VimVaderSynNotPatRange	contained	"\\\\\|\\\["
syn match	VimVaderMtchComment	contained	'"[^"]\+$'
syn cluster VimVaderFuncBodyList add=VimVaderSynType

" Syntax: sync {{{2
" ============
syn keyword VimVaderSynType	contained	sync	skipwhite	nextgroup=VimVaderSyncC,vimSyncLines,vimSyncMatch,vimSyncError,vimSyncLinebreak,vimSyncLinecont,vimSyncRegion
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_novimsyncerror")
 syn match	VimVaderSyncError	contained	"\i\+"
endif
syn keyword	VimVaderSyncC	contained	ccomment	clear	fromstart
syn keyword	VimVaderSyncMatch	contained	match	skipwhite	nextgroup=VimVaderSyncGroupName
syn keyword	VimVaderSyncRegion	contained	region	skipwhite	nextgroup=VimVaderSynReg
syn match	VimVaderSyncLinebreak	contained	"\<linebreaks="	skipwhite	nextgroup=VimVaderNumber
syn keyword	VimVaderSyncLinecont	contained	linecont	skipwhite	nextgroup=VimVaderSynRegPat
syn match	VimVaderSyncLines	contained	"\(min\|max\)\=lines="	nextgroup=VimVaderNumber
syn match	VimVaderSyncGroupName	contained	"\h\w*"	skipwhite	nextgroup=VimVaderSyncKey
syn match	VimVaderSyncKey	contained	"\<groupthere\|grouphere\>"	skipwhite nextgroup=VimVaderSyncGroup
syn match	VimVaderSyncGroup	contained	"\h\w*"	skipwhite	nextgroup=VimVaderSynRegPat,vimSyncNone
syn keyword	VimVaderSyncNone	contained	NONE

" Additional IsCommand, here by reasons of precedence {{{2
" ====================
syn match	VimVaderIsCommand	"<Bar>\s*\a\+"	transparent contains=VimVaderCommand,vimNotation

" Highlighting {{{2
" ============
syn cluster	VimVaderHighlightCluster		contains=VimVaderHiLink,vimHiClear,vimHiKeyList,vimComment
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_novimhictermerror")
 syn match	VimVaderHiCtermError	contained	"\D\i*"
endif
syn match	VimVaderHighlight	"\<hi\%[ghlight]\>"	skipwhite nextgroup=VimVaderHiBang,@vimHighlightCluster
syn match	VimVaderHiBang	contained	"!"	skipwhite nextgroup=@vimHighlightCluster

syn match	VimVaderHiGroup	contained	"\i\+"
syn case ignore
syn keyword	VimVaderHiAttrib	contained	none bold inverse italic nocombine reverse standout strikethrough underline undercurl
syn keyword	VimVaderFgBgAttrib	contained	none bg background fg foreground
syn case match
syn match	VimVaderHiAttribList	contained	"\i\+"	contains=VimVaderHiAttrib
syn match	VimVaderHiAttribList	contained	"\i\+,"he=e-1	contains=VimVaderHiAttrib nextgroup=VimVaderHiAttribList
syn case ignore
syn keyword	VimVaderHiCtermColor	contained	black blue brown cyan darkblue darkcyan darkgray darkgreen darkgrey darkmagenta darkred darkyellow gray green grey lightblue lightcyan lightgray lightgreen lightgrey lightmagenta lightred magenta red white yellow
syn match	VimVaderHiCtermColor	contained	"\<color\d\{1,3}\>"

syn case match
syn match	VimVaderHiFontname	contained	"[a-zA-Z\-*]\+"
syn match	VimVaderHiGuiFontname	contained	"'[a-zA-Z\-* ]\+'"
syn match	VimVaderHiGuiRgb	contained	"#\x\{6}"

" Highlighting: hi group key=arg ... {{{2
syn cluster	VimVaderHiCluster contains=VimVaderGroup,vimHiBlend,vimHiGroup,vimHiTerm,vimHiCTerm,vimHiStartStop,vimHiCtermFgBg,vimHiGui,vimHiGuiFont,vimHiGuiFgBg,vimHiKeyError,vimNotation
syn region	VimVaderHiKeyList	contained oneline start="\i\+" skip="\\\\\|\\|" end="$\||"	contains=@vimHiCluster
if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_vimhikeyerror")
 syn match	VimVaderHiKeyError	contained	"\i\+="he=e-1
endif
syn match	VimVaderHiTerm	contained	"\cterm="he=e-1		nextgroup=VimVaderHiAttribList
syn match	VimVaderHiStartStop	contained	"\c\(start\|stop\)="he=e-1	nextgroup=VimVaderHiTermcap,vimOption
syn match	VimVaderHiCTerm	contained	"\ccterm="he=e-1		nextgroup=VimVaderHiAttribList
syn match	VimVaderHiCtermFgBg	contained	"\ccterm[fb]g="he=e-1	nextgroup=VimVaderHiNmbr,vimHiCtermColor,vimFgBgAttrib,vimHiCtermError
syn match	VimVaderHiGui	contained	"\cgui="he=e-1		nextgroup=VimVaderHiAttribList
syn match	VimVaderHiGuiFont	contained	"\cfont="he=e-1		nextgroup=VimVaderHiFontname
syn match	VimVaderHiGuiFgBg	contained	"\cgui\%([fb]g\|sp\)="he=e-1	nextgroup=VimVaderHiGroup,vimHiGuiFontname,vimHiGuiRgb,vimFgBgAttrib
syn match	VimVaderHiTermcap	contained	"\S\+"		contains=VimVaderNotation
syn match	VimVaderHiBlend	contained	"\cblend="he=e-1		nextgroup=VimVaderHiNmbr
syn match	VimVaderHiNmbr	contained	'\d\+'

" Highlight: clear {{{2
syn keyword	VimVaderHiClear	contained	clear	nextgroup=VimVaderHiGroup

" Highlight: link {{{2
" see tst24 (hi def vs hi) (Jul 06, 2018)
"syn region	VimVaderHiLink	contained oneline matchgroup=VimVaderCommand start="\(\<hi\%[ghlight]\s\+\)\@<=\(\(def\%[ault]\s\+\)\=link\>\|\<def\>\)" end="$"	contains=VimVaderHiGroup,vimGroup,vimHLGroup,vimNotation
syn region	VimVaderHiLink	contained oneline matchgroup=VimVaderCommand start="\(\<hi\%[ghlight]\s\+\)\@<=\(\(def\%[ault]\s\+\)\=link\>\|\<def\>\)" end="$"	contains=@vimHiCluster
syn cluster VimVaderFuncBodyList add=VimVaderHiLink

" Control Characters {{{2
" ==================
syn match	VimVaderCtrlChar	"[--]"

" Beginners - Patterns that involve ^ {{{2
" =========
syn match	VimVaderLineComment	+^[ \t:]*".*$+	contains=@vimCommentGroup,vimCommentString,vimCommentTitle
syn match	VimVaderCommentTitle	'"\s*\%([sS]:\|\h\w*#\)\=\u\w*\(\s\+\u\w*\)*:'hs=s+1	contained contains=VimVaderCommentTitleLeader,vimTodo,@vimCommentGroup
syn match	VimVaderContinue	"^\s*\\"
syn region	VimVaderString	start="^\s*\\\z(['"]\)" skip='\\\\\|\\\z1' end="\z1" oneline keepend contains=@vimStringGroup,vimContinue
syn match	VimVaderCommentTitleLeader	'"\s\+'ms=s+1	contained

" Searches And Globals: {{{2
" ====================
syn match	VimVaderSearch	'^\s*[/?].*'		contains=VimVaderSearchDelim
syn match	VimVaderSearchDelim	'^\s*\zs[/?]\|[/?]$'	contained
syn region	VimVaderGlobal	matchgroup=Statement start='\<g\%[lobal]!\=/'  skip='\\.' end='/'	skipwhite nextgroup=VimVaderSubst
syn region	VimVaderGlobal	matchgroup=Statement start='\<v\%[global]!\=/' skip='\\.' end='/'	skipwhite nextgroup=VimVaderSubst

" ====================
" Highlighting Settings {{{2
" ====================

if !exists("skip_vim_syntax_inits")
 hi def link VimVaderAbb	VimVaderCommand
 hi def link VimVaderAddress	VimVaderMark
 hi def link VimVaderAugroupError	VimVaderError
 hi def link VimVaderAugroupKey	VimVaderCommand
 hi def link VimVaderAuHighlight	VimVaderHighlight
 hi def link VimVaderAutoCmdOpt	VimVaderOption
 hi def link VimVaderAutoCmd	VimVaderCommand
 hi def link VimVaderAutoEvent	Type
 hi def link VimVaderAutoSet	VimVaderCommand
 hi def link VimVaderBehaveModel	VimVaderBehave
 hi def link VimVaderBehave	VimVaderCommand
 hi def link VimVaderBracket	Delimiter
 hi def link VimVaderCmplxRepeat	SpecialChar
 hi def link VimVaderCommand	Statement
 hi def link VimVaderComment	Comment
 hi def link VimVaderCommentString	VimVaderString
 hi def link VimVaderCommentTitle	PreProc
 hi def link VimVaderCondHL	VimVaderCommand
 hi def link VimVaderContinue	Special
 hi def link VimVaderCtrlChar	SpecialChar
 hi def link VimVaderEchoHLNone	VimVaderGroup
 hi def link VimVaderEchoHL	VimVaderCommand
 hi def link VimVaderElseIfErr	Error
 hi def link VimVaderElseif	VimVaderCondHL
 hi def link VimVaderEnvvar	PreProc
 hi def link VimVaderError	Error
 hi def link VimVaderFBVar	VimVaderVar
 hi def link VimVaderFgBgAttrib	VimVaderHiAttrib
 hi def link VimVaderFold	Folded
 hi def link VimVaderFTCmd	VimVaderCommand
 hi def link VimVaderFTOption	VimVaderSynType
 hi def link VimVaderFunc           Function
 hi def link VimVaderFuncKey	VimVaderCommand
 hi def link VimVaderFuncName	Function
 hi def link VimVaderFuncSID	Special
 hi def link VimVaderFuncVar	Identifier
 hi def link VimVaderGroupAdd	VimVaderSynOption
 hi def link VimVaderGroupName	VimVaderGroup
 hi def link VimVaderGroupRem	VimVaderSynOption
 hi def link VimVaderGroupSpecial	Special
 hi def link VimVaderGroup	Type
 hi def link VimVaderHiAttrib	PreProc
 hi def link VimVaderHiBlend	VimVaderHiTerm
 hi def link VimVaderHiClear	VimVaderHighlight
 hi def link VimVaderHiCtermFgBg	VimVaderHiTerm
 hi def link VimVaderHiCTerm	VimVaderHiTerm
 hi def link VimVaderHighlight	VimVaderCommand
 hi def link VimVaderHiGroup	VimVaderGroupName
 hi def link VimVaderHiGuiFgBg	VimVaderHiTerm
 hi def link VimVaderHiGuiFont	VimVaderHiTerm
 hi def link VimVaderHiGuiRgb	VimVaderNumber
 hi def link VimVaderHiGui	VimVaderHiTerm
 hi def link VimVaderHiNmbr	Number
 hi def link VimVaderHiStartStop	VimVaderHiTerm
 hi def link VimVaderHiTerm	Type
 hi def link VimVaderHLGroup	VimVaderGroup
 hi def link VimVaderHLMod	PreProc
 hi def link VimVaderInsert	VimVaderString
 hi def link VimVaderIskSep	Delimiter
 hi def link VimVaderKeyCode	VimVaderSpecFile
 hi def link VimVaderKeyword	Statement
 hi def link VimVaderLet	VimVaderCommand
 hi def link VimVaderLineComment	VimVaderComment
 hi def link VimVaderMapBang	VimVaderCommand
 hi def link VimVaderMapModKey	VimVaderFuncSID
 hi def link VimVaderMapMod	VimVaderBracket
 hi def link VimVaderMap	VimVaderCommand
 hi def link VimVaderMark	Number
 hi def link VimVaderMarkNumber	VimVaderNumber
 hi def link VimVaderMenuMod	VimVaderMapMod
 hi def link VimVaderMenuNameMore	VimVaderMenuName
 hi def link VimVaderMenuName	PreProc
 hi def link VimVaderMtchComment	VimVaderComment
 hi def link VimVaderNorm	VimVaderCommand
 hi def link VimVaderNotation	Special
 hi def link VimVaderNotFunc	VimVaderCommand
 hi def link VimVaderNotPatSep	VimVaderString
 hi def link VimVaderNumber	Number
 hi def link VimVaderOperError	Error
 hi def link VimVaderOper	Operator
 hi def link VimVaderOperParen	String
 hi def link VimVaderOption	PreProc
 hi def link VimVaderParenSep	Delimiter
 hi def link VimVaderPatSepErr	VimVaderError
 hi def link VimVaderPatSepR	VimVaderPatSep
 hi def link VimVaderPatSep	SpecialChar
 hi def link VimVaderPatSepZone	VimVaderString
 hi def link VimVaderPatSepZ	VimVaderPatSep
 hi def link VimVaderPattern	Type
 hi def link VimVaderPlainMark	VimVaderMark
 hi def link VimVaderPlainRegister	VimVaderRegister
 hi def link VimVaderRegister	SpecialChar
 hi def link VimVaderScriptDelim	Comment
 hi def link VimVaderSearchDelim	Statement
 hi def link VimVaderSearch	VimVaderString
 hi def link VimVaderSep	Delimiter
 hi def link VimVaderSetMod	VimVaderOption
 hi def link VimVaderSetSep	Statement
 hi def link VimVaderSetString	VimVaderString
 hi def link VimVaderSpecFile	Identifier
 hi def link VimVaderSpecFileMod	VimVaderSpecFile
 hi def link VimVaderSpecial	Type
 hi def link VimVaderStatement	Statement
 hi def link VimVaderStringCont	VimVaderString
 hi def link VimVaderString	String
 hi def link VimVaderStringEnd	VimVaderString
 hi def link VimVaderSubst1	VimVaderSubst
 hi def link VimVaderSubstDelim	Delimiter
 hi def link VimVaderSubstFlags	Special
 hi def link VimVaderSubstSubstr	SpecialChar
 hi def link VimVaderSubstTwoBS	VimVaderString
 hi def link VimVaderSubst	VimVaderCommand
 hi def link VimVaderSynCaseError	Error
 hi def link VimVaderSynCase	Type
 hi def link VimVaderSyncC	Type
 hi def link VimVaderSyncError	Error
 hi def link VimVaderSyncGroupName	VimVaderGroupName
 hi def link VimVaderSyncGroup	VimVaderGroupName
 hi def link VimVaderSyncKey	Type
 hi def link VimVaderSyncNone	Type
 hi def link VimVaderSynContains	VimVaderSynOption
 hi def link VimVaderSynError	Error
 hi def link VimVaderSynKeyContainedin	VimVaderSynContains
 hi def link VimVaderSynKeyOpt	VimVaderSynOption
 hi def link VimVaderSynMtchGrp	VimVaderSynOption
 hi def link VimVaderSynMtchOpt	VimVaderSynOption
 hi def link VimVaderSynNextgroup	VimVaderSynOption
 hi def link VimVaderSynNotPatRange	VimVaderSynRegPat
 hi def link VimVaderSynOption	Special
 hi def link VimVaderSynPatRange	VimVaderString
 hi def link VimVaderSynRegOpt	VimVaderSynOption
 hi def link VimVaderSynRegPat	VimVaderString
 hi def link VimVaderSynReg	Type
 hi def link VimVaderSyntax	VimVaderCommand
 hi def link VimVaderSynType	VimVaderSpecial
 hi def link VimVaderTodo	Todo
 hi def link VimVaderUnmap	VimVaderMap
 hi def link VimVaderUserAttrbCmpltFunc	Special
 hi def link VimVaderUserAttrbCmplt	VimVaderSpecial
 hi def link VimVaderUserAttrbKey	VimVaderOption
 hi def link VimVaderUserAttrb	VimVaderSpecial
 hi def link VimVaderUserAttrbError	Error
 hi def link VimVaderUserCmdError	Error
 hi def link VimVaderUserCommand	VimVaderCommand
 hi def link VimVaderUserFunc	Function
 hi def link VimVaderVar	Identifier
 hi def link VimVaderWarn	WarningMsg

 hi def link nvimAutoEvent	VimVaderAutoEvent
 hi def link nvimHLGroup	VimVaderHLGroup
 hi def link nvimMap	VimVaderMap
 hi def link nvimUnmap	VimVaderUnmap
endif
" vim:ts=18  fdm=marker
